
-- 1번

SELECT EMP_ID, EMP_NAME, PHONE, HIRE_DATE, DEPT_TITLE
FROM EMPLOYEE
JOIN DEPARTMENT ON(DEPT_ID = DEPT_CODE)
WHERE DEPT_CODE = (SELECT DEPT_CODE FROM EMPLOYEE  WHERE EMP_NAME = '전지연')
AND EMP_NAME <> '전지연';


-- 2번

SELECT EMP_ID , EMP_NAME , PHONE , SALARY , JOB_NAME
FROM EMPLOYEE
NATURAL JOIN JOB
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEE WHERE EXTRACT(YEAR FROM HIRE_DATE) >= 2000);

-- 3번

SELECT EMP_ID , EMP_NAME , DEPT_CODE , JOB_CODE , DEPT_TITLE, JOB_NAME
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
NATURAL JOIN JOB
WHERE (DEPT_CODE, JOB_CODE) IN (SELECT DEPT_CODE, JOB_CODE FROM EMPLOYEE WHERE EMP_NAME ='노옹철')
AND EMP_NAME <> '노옹철';



-- 4번

SELECT EMP_ID ,EMP_NAME,JOB_CODE, HIRE_DATE
FROM EMPLOYEE
WHERE (DEPT_CODE, JOB_CODE ) IN 
(SELECT DEPT_CODE, JOB_CODE FROM EMPLOYEE 
WHERE EXTRACT(YEAR FROM HIRE_DATE) = 2000);




-- 5번



SELECT EMP_ID , EMP_NAME , DEPT_CODE , MANAGER_ID , EMP_NO , HIRE_DATE 
FROM EMPLOYEE
WHERE (DEPT_CODE, MANAGER_ID) IN
(SELECT DEPT_CODE, MANAGER_ID FROM EMPLOYEE
WHERE SUBSTR(EMP_NO, 8, 1) = 2 
AND SUBSTR(EMP_NO, 1, 2) = 77);



-- 6번



SELECT EMP_ID , EMP_NAME , NVL(DEPT_TITLE, '소속없음'), JOB_NAME, HIRE_DATE
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
JOIN JOB USING(JOB_CODE)
WHERE (DEPT_CODE, HIRE_DATE) IN (SELECT DEPT_CODE, MIN(HIRE_DATE) FROM EMPLOYEE WHERE ENT_YN = 'N'
GROUP BY DEPT_CODE)
ORDER BY HIRE_DATE;


-- 7번


SELECT EMP_ID , EMP_NAME , JOB_NAME,
ABS(EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO , 1 , 6), 'RRMMDD')) - EXTRACT(YEAR FROM SYSDATE)) 나이
,TO_CHAR((SALARY * 12) + (SALARY * NVL(BONUS, '1') * 12), 'L999,999,999') 연봉
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
WHERE (JOB_CODE, 
ABS(EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO , 1 , 6), 'RRMMDD')) - EXTRACT(YEAR FROM SYSDATE)))
IN (SELECT JOB_CODE,
MIN(ABS(EXTRACT(YEAR FROM TO_DATE(SUBSTR(EMP_NO , 1 , 6), 'RRMMDD')) - EXTRACT(YEAR FROM SYSDATE))) 나이
FROM EMPLOYEE GROUP BY JOB_CODE)
ORDER BY 나이 DESC;






